## Find near-mind sentences to first sentence

### Create list of all words

In [2]:
import pandas as pd
import re
file_obj = open('sentences.txt','r')        #Read file
lines = file_obj.readlines()                
all_words=[]
for line in lines:
    line=line.lower().strip()  
    result=re.split(r'[^a-z]', line)        #Cut symbols
    line=' '.join(result).split()
    all_words += line                       #Concatenate lists of lines to one list
print(all_words)

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that',

In [3]:
print(len(all_words))

484


### Create dictionary of unique words with indexes 

In [4]:
dict1={}
count=0
for i in all_words:
    if i not in dict1:
        dict1[i]=count
        count += 1
    else:
        continue

print(dict1)


{'in': 0, 'comparison': 1, 'to': 2, 'dogs': 3, 'cats': 4, 'have': 5, 'not': 6, 'undergone': 7, 'major': 8, 'changes': 9, 'during': 10, 'the': 11, 'domestication': 12, 'process': 13, 'as': 14, 'cat': 15, 'simply': 16, 'catenates': 17, 'streams': 18, 'of': 19, 'bytes': 20, 'it': 21, 'can': 22, 'be': 23, 'also': 24, 'used': 25, 'concatenate': 26, 'binary': 27, 'files': 28, 'where': 29, 'will': 30, 'just': 31, 'sequence': 32, 'a': 33, 'common': 34, 'interactive': 35, 'use': 36, 'for': 37, 'single': 38, 'file': 39, 'is': 40, 'output': 41, 'content': 42, 'standard': 43, 'hear': 44, 'sounds': 45, 'too': 46, 'faint': 47, 'or': 48, 'high': 49, 'frequency': 50, 'human': 51, 'ears': 52, 'such': 53, 'those': 54, 'made': 55, 'by': 56, 'mice': 57, 'and': 58, 'other': 59, 'small': 60, 'animals': 61, 'one': 62, 'people': 63, 'deliberately': 64, 'tamed': 65, 'artificial': 66, 'selection': 67, 'they': 68, 'were': 69, 'useful': 70, 'predators': 71, 'vermin': 72, 'domesticated': 73, 'its': 74, 'closest': 

### Create matrix 

In [5]:
import numpy as np
A=np.zeros((len(lines),len(dict1)))
A.shape

(22, 254)

### Fill matrix with counters of words in each line

In [6]:
for line in range(len(lines)):
    list_words=lines[line].lower().strip()
    result=re.split(r'[^a-z]', list_words)
    list_words=' '.join(result).split()
   
    dict2={}
    
    for word in list_words:            #Count words in line
        if word not in dict2:
            dict2[word] = 1
        else:
            dict2[word] += 1
        j=dict1[word]                
        A[line,j]=dict2[word]         #Write/rewrite count in cell
        
        
print(A)
print(A.shape)


[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]
(22, 254)


### Find cosine distance to first line

In [14]:
from scipy.spatial.distance import cosine        
list_cos=[]
dict_cos={}
count_cos=0
for p in range(A.shape[0]):
    list_cos.append(cosine(A[0], A[p]))        #Fill list of cosine distance

for i in range(len(list_cos)):                 #Create dictionary to find indexes of cosine distance values
    if list_cos[i] not in dict_cos:
        dict_cos[list_cos[i]]=count_cos
        count_cos += 1
    else:
        continue

for i, v in sorted(dict_cos.items()):          #Sort dictionary to find most near-mind lines to first line
    print(i, v)
    
        

{0.0: 0, 0.9527544408738466: 1, 0.8644738145642124: 2, 0.8951715163278082: 3, 0.7770887149698589: 4, 0.9402385695332803: 5, 0.7327387580875756: 6, 0.9258750683338899: 7, 0.8842724875284311: 8, 0.9055088817476932: 9, 0.8328165362273942: 10, 0.8804771390665607: 11, 0.8396432548525454: 12, 0.8703592552895671: 13, 0.8740118423302576: 14, 0.9442721787424647: 15, 0.8406361854220809: 16, 0.956644501523794: 17, 0.8885443574849294: 18, 0.8427572744917122: 19, 0.8250364469440588: 20}
0.0 0
0.7327387580875756 6
0.7770887149698589 4
0.8250364469440588 20
0.8328165362273942 10
0.8396432548525454 12
0.8406361854220809 16
0.8427572744917122 19
0.8644738145642124 2
0.8703592552895671 13
0.8740118423302576 14
0.8804771390665607 11
0.8842724875284311 8
0.8885443574849294 18
0.8951715163278082 3
0.9055088817476932 9
0.9258750683338899 7
0.9402385695332803 5
0.9442721787424647 15
0.9527544408738466 1
0.956644501523794 17
